version: '3.8'

services:
  pcstore-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pcstore/public/images:/app/images
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:pcstorepassword@mongo:27017/pcstore?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: pc-store-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pcstorepassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
