myapp:
  image-directory: 'file:./pcstore/public/images/'

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pcstore_db
      database: pcstore_db
      uuid-representation: standard

logging:
  level:
    org:
      springframework:
        data:
          mongodb=DEBUG:
