spring:
  application:
    name: pcstore-app
  data:
    mongodb:
      uri: mongodb://root:pcstorepassword@mongo:27017/pcstore_db?authSource=admin
      uuid-representation: standard

# Configuraci贸n directorio de imagenes
myapp:
  image-directory: 'file:/app/images/'

# Configuraciones de logging
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    "[org.springframework]": ERROR
    "[com.pcstore]": INFO

# Configuraci贸n del servidor, en caso de que necesites especificar un puerto diferente o propiedades relacionadas
server:
  port: 8080

# Configuraciones de documentaci贸n API si decides integrar Swagger o similar en el futuro
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorted: method
  api-docs:
    enable: true
    path: "/api-docs"

# Configuraci贸n de manejo de errores y mensajes, similar al ejemplo anterior
messages:
  errorMessage: "An error occurred. Please try again later."
